blank_issues_enabled: false
contact_links:
  - name: Questions about CCTC training
    url: https://github.com/JPichardo170A/169CPT-CCTC/issues
    about: For general questions about the training materials
